server:
    port: 8099
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: xxx
    username: xxx
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
    mapper-locations:
      - classpath:**/mapper/xml/*.xml
    type-aliases-package: com.qujiali.springboot.entity
    global-config:
        logic-delete-value: 0
        logic-not-delete-value: 1
        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

